"""someupdates in user model colum

Revision ID: 494e03c7f029
Revises: 02898189751b
Create Date: 2025-09-17 04:22:08.061618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494e03c7f029'
down_revision: Union[str, Sequence[str], None] = '02898189751b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status_2fa'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_status_2fa'), 'users', ['status_2fa'], unique=False)
    # ### end Alembic commands ###
