"""added google_id in user table

Revision ID: 4bc3a9f1a5ae
Revises: c2587dfd82fd
Create Date: 2025-09-25 04:35:54.567867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc3a9f1a5ae'
down_revision: Union[str, Sequence[str], None] = 'c2587dfd82fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
