"""removed the unique true from user secret_2fa

Revision ID: 4f1ce1e88179
Revises: a1cf4fbaf050
Create Date: 2025-10-15 18:22:22.705185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1ce1e88179'
down_revision: Union[str, Sequence[str], None] = 'a1cf4fbaf050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
