"""active or in active date added in user column

Revision ID: 5ef456dbb0bc
Revises: d0fff8a60c67
Create Date: 2025-09-20 02:33:43.202995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef456dbb0bc'
down_revision: Union[str, Sequence[str], None] = 'd0fff8a60c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('in_active_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'in_active_date')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
