"""added logging table

Revision ID: 902cd29ef3ad
Revises: 5ef456dbb0bc
Create Date: 2025-09-22 21:24:46.345124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902cd29ef3ad'
down_revision: Union[str, Sequence[str], None] = '5ef456dbb0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loglevel', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_source', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logging_id'), 'logging', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logging_id'), table_name='logging')
    op.drop_table('logging')
    # ### end Alembic commands ###
