"""added google_id nullable  in user table

Revision ID: a1cf4fbaf050
Revises: 4bc3a9f1a5ae
Create Date: 2025-09-25 04:36:36.892900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cf4fbaf050'
down_revision: Union[str, Sequence[str], None] = '4bc3a9f1a5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
