"""added payment method column in transaction table

Revision ID: d0fff8a60c67
Revises: 494e03c7f029
Create Date: 2025-09-18 19:28:21.256507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fff8a60c67'
down_revision: Union[str, Sequence[str], None] = '494e03c7f029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
